### ISSUE TITLE
java.net.NoRouteToHostException thrown when 2 com.github.dreamhead.moco.HttpServer are started and stopped in the same Thread

### ISSUE THREAD

**Issue by thomas-rc-hutchinson** [dreamhead/moco#127]
The exception is thrown at runner2.stop().

```Java
public static void main(String[] args){
        HttpServer moco = httpserver(8080);
        moco.response("blank");
        Runner runner = runner(moco);
        runner.start();
        runner.stop();

        HttpServer moco2 = httpserver(8081);
        moco2.response("blank");
        Runner runner2 = runner(moco2);
        runner2.start();
        runner2.stop();
    }
```

```Java
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: java.net.NoRouteToHostException: No route to host
	at com.github.dreamhead.moco.internal.Awaiter.await(Awaiter.java:36)
	at com.github.dreamhead.moco.internal.Awaiter.awaitUntil(Awaiter.java:55)
	at com.github.dreamhead.moco.internal.MocoServer.stop(MocoServer.java:49)
	at com.github.dreamhead.moco.internal.MocoHttpServer.stop(MocoHttpServer.java:60)
	at com.williamhill.lotteries.healthcheck.oxi.AbstractOXiHealthcheckUTest.main(AbstractOXiHealthcheckUTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.RuntimeException: java.net.NoRouteToHostException: No route to host
	at com.github.dreamhead.moco.internal.MocoServer$1.call(MocoServer.java:83)
	at com.github.dreamhead.moco.internal.MocoServer$1.call(MocoServer.java:73)
	at com.github.dreamhead.moco.internal.Awaiter$1.run(Awaiter.java:19)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.NoRouteToHostException: No route to host
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:198)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at java.net.Socket.connect(Socket.java:528)
	at com.github.dreamhead.moco.internal.MocoServer$1.call(MocoServer.java:78)
	... 9 more
```

I have looked at the internals and see that socket.connect(address) is throwing a NoRouteToHostException in MocoServer.

```Java
private Callable<Boolean> serverIsClosed(final InetSocketAddress address) {
        return new Callable<Boolean>() {
            @Override
            public Boolean call() throws Exception {
                try {
                    Socket socket = new Socket();
                    socket.connect(address);
                    return false;
                } catch (ConnectException e) {
                    return true;
                } catch (Exception e) {
                    throw new RuntimeException(e);
                }
            }
        };
    }
```

I placed a 3 second sleep between runner.stop and HttpServer moco2 = httpserver(8081);. This fixed the issue and no Exception was thrown. Also I wrapped both servers in there own Thread and it worked. Seems like a timing issue. Has anyone ever had this issue? Maybe something needs to be configured in my OS (Fedora).

Is this issue known?

**Comment by dreamhead** [comment]
Which version are you using? It seems that serverIsClosed has been removed in latest version. 

I've tried your code with latest Moco, and it works well.

**Comment by thomas-rc-hutchinson** [comment]
It was 0.9.2, I upgraded to 0.10.2 and I no longer see the issue. Thank you.
