### ISSUE TITLE
Moco httpServer not handling incoming gzipped content for matchers

### ISSUE THREAD

**Issue by jerrylawson** [dreamhead/moco#138]
We've been using httpServer successfully for a while. We create matchers that match on URL, headers and body contents. Recently, there was a change to our Jersey client code that enabled gzipping the body of PUT/POST/DELETE requests. Now, the MocoHandler throws exceptions when attempting to process the incoming request that has a gzipped body. Here is what we see when running our tests against httpServer (with a RequestMonitor for logging):

POST /apikey HTTP/1.1
Accept: application/json
Content-Type: application/json
Content-Encoding: gzip
Host: localhost:56780
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.1 (Java/1.8.0_66)
Accept-Encoding: gzip,deflate
Content-Length: 527

Exception thrown:

io.netty.handler.codec.http.multipart.HttpPostRequestDecoder$ErrorDataDecoderException: Bad string: [ed: unprintable characters here]
	at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.decodeAttribute(HttpPostStandardRequestDecoder.java:651)
	at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.parseBodyAttributes(HttpPostStandardRequestDecoder.java:542)
	at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.parseBody(HttpPostStandardRequestDecoder.java:367)
	at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.offer(HttpPostStandardRequestDecoder.java:301)
	at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.<init>(HttpPostStandardRequestDecoder.java:163)
	at io.netty.handler.codec.http.multipart.HttpPostRequestDecoder.<init>(HttpPostRequestDecoder.java:107)
	at io.netty.handler.codec.http.multipart.HttpPostRequestDecoder.<init>(HttpPostRequestDecoder.java:54)
	at com.github.dreamhead.moco.extractor.FormsRequestExtractor.doExtract(FormsRequestExtractor.java:26)
	at com.github.dreamhead.moco.HttpRequestExtractor.extract(HttpRequestExtractor.java:10)
	at com.github.dreamhead.moco.extractor.FormRequestExtractor.doExtract(FormRequestExtractor.java:20)
	at com.github.dreamhead.moco.HttpRequestExtractor.extract(HttpRequestExtractor.java:10)
	at com.github.dreamhead.moco.matcher.AbstractOperatorMatcher.match(AbstractOperatorMatcher.java:30)
	at com.github.dreamhead.moco.matcher.AndRequestMatcher.match(AndRequestMatcher.java:14)
	at com.github.dreamhead.moco.matcher.AndRequestMatcher.match(AndRequestMatcher.java:14)
	at com.github.dreamhead.moco.setting.BaseSetting.match(BaseSetting.java:22)
	at com.github.dreamhead.moco.internal.MocoHandler.doGetHttpResponse(MocoHandler.java:74)
	at com.github.dreamhead.moco.internal.MocoHandler.getHttpResponse(MocoHandler.java:59)
	at com.github.dreamhead.moco.internal.MocoHandler.handleRequest(MocoHandler.java:49)
	at com.github.dreamhead.moco.internal.MocoHandler.channelRead0(MocoHandler.java:38)
	at com.github.dreamhead.moco.internal.MocoHandler.channelRead0(MocoHandler.java:24)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:147)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:110)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: invalid escape sequence `[ed:unprintable chars]' at index 10 of: [ed:unprintable chars]
	at io.netty.handler.codec.http.QueryStringDecoder.decodeComponent(QueryStringDecoder.java:352)
	at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.decodeAttribute(HttpPostStandardRequestDecoder.java:649)
	... 38 more

Response return:

HTTP/1.1 400

If we change our Jersey client to NOT gzip the PUT/POST/DELETE body, everything works as expected.

Is there a way to configure moco's httpServer to accept and process gzipped bodies when processing body matchers?

**Comment by dreamhead** [comment]
Could you please provide your Moco configuration and your request content? I'll try to reproduce your issue.
