### ISSUE TITLE
proxy模式下，post请求会报 ERROR Failed to load remote and try to failover

### ISSUE THREAD

**Issue by LmangoLemon** [dreamhead/moco#224]
19 一月 2018 22:58:12 [nioEventLoopGroup-3-9] INFO  Request received:

POST /test1 HTTP/1.1
Host: 127.0.0.1
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.2 (Java/1.8.0_131)
Accept-Encoding: gzip,deflate
content-length: 0

19 一月 2018 22:58:12 [nioEventLoopGroup-3-9] ERROR Failed to load remote and try to failover
org.apache.http.client.ClientProtocolException: null
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:187)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at com.github.dreamhead.moco.handler.AbstractProxyResponseHandler.doForward(AbstractProxyResponseHandler.java:259)
        at com.github.dreamhead.moco.handler.AbstractProxyResponseHandler.doProxy(AbstractProxyResponseHandler.java:253)
        at com.github.dreamhead.moco.handler.AbstractProxyResponseHandler.doWriteToResponse(AbstractProxyResponseHandler.java:232)
        at com.github.dreamhead.moco.handler.AbstractHttpResponseHandler.writeToResponse(AbstractHttpResponseHandler.java:20)
        at com.github.dreamhead.moco.setting.BaseSetting.writeToResponse(BaseSetting.java:35)
        at com.github.dreamhead.moco.internal.MocoHandler.doGetHttpResponse(MocoHandler.java:77)
        at com.github.dreamhead.moco.internal.MocoHandler.getHttpResponse(MocoHandler.java:61)
        at com.github.dreamhead.moco.internal.MocoHandler.handleRequest(MocoHandler.java:51)
        at com.github.dreamhead.moco.internal.MocoHandler.channelRead0(MocoHandler.java:40)
        at com.github.dreamhead.moco.internal.MocoHandler.channelRead0(MocoHandler.java:25)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.http.ProtocolException: Content-Length header already present
        at org.apache.http.protocol.RequestContent.process(RequestContent.java:97)
        at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:133)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:183)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        ... 39 common frames omitted
19 一月 2018 22:58:12 [nioEventLoopGroup-3-9] ERROR Exception thrown
com.github.dreamhead.moco.MocoException: no failover response found
        at com.github.dreamhead.moco.handler.failover.FailoverExecutor$1.failover(FailoverExecutor.java:18)
        at com.github.dreamhead.moco.handler.failover.Failover.failover(Failover.java:19)
        at com.github.dreamhead.moco.handler.AbstractProxyResponseHandler.doForward(AbstractProxyResponseHandler.java:262)
        at com.github.dreamhead.moco.handler.AbstractProxyResponseHandler.doProxy(AbstractProxyResponseHandler.java:253)
        at com.github.dreamhead.moco.handler.AbstractProxyResponseHandler.doWriteToResponse(AbstractProxyResponseHandler.java:232)
        at com.github.dreamhead.moco.handler.AbstractHttpResponseHandler.writeToResponse(AbstractHttpResponseHandler.java:20)
        at com.github.dreamhead.moco.setting.BaseSetting.writeToResponse(BaseSetting.java:35)
        at com.github.dreamhead.moco.internal.MocoHandler.doGetHttpResponse(MocoHandler.java:77)
        at com.github.dreamhead.moco.internal.MocoHandler.getHttpResponse(MocoHandler.java:61)
        at com.github.dreamhead.moco.internal.MocoHandler.handleRequest(MocoHandler.java:51)
        at com.github.dreamhead.moco.internal.MocoHandler.channelRead0(MocoHandler.java:40)
        at com.github.dreamhead.moco.internal.MocoHandler.channelRead0(MocoHandler.java:25)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Unknown Source)
19 一月 2018 22:58:12 [nioEventLoopGroup-3-9] INFO  Response return:

HTTP/1.1 400

**Comment by LmangoLemon** [comment]
这是配置文件
 {
  "request" :
    {
      "uri" : "/test1",
	  "method": "post"
    },
  "response" :
    {
      "proxy" : "http://127.0.0.1:8080/test"
    }
}

这是直接调用此接口的响应
![image](https://user-images.githubusercontent.com/32920122/35179220-dc1a5e02-fdd0-11e7-8ba8-080c6f021230.png)

帮看看这里是哪里有问题吗？

**Comment by dreamhead** [comment]
The exception means that Moco proxy fail to reach your remote server. It will try to failover from your local failover file.

In general, please make suer your remote server is available.
