### ISSUE TITLE
how to manage the json file

### ISSUE THREAD

**Issue by HelloXiaoHe** [dreamhead/moco#225]
hi,dashen.
the standalone server start with json file, 
it means all the request/response will put in a file 
is there anyway to start without json file, 
scan the catalog to get the request/response?

**Comment by HelloXiaoHe** [comment]
oh,i see the doc
https://github.com/dreamhead/moco/blob/master/moco-doc/cmd.md#many-configuration-files

java  -Dfile.encoding=UTF-8 -jar moco-runner-0.12.0-standalone.jar http -p 8080 -c "*.json"

but it start with exception
[main] ERROR Illegal char <*> at index 0: *.json

**Comment by HelloXiaoHe** [comment]
java.nio.file.InvalidPathException: Illegal char <*> at index 27: src/test/resources/details/*.json

	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at com.github.dreamhead.moco.util.Globs.getGlobPath(Globs.java:31)
	at com.github.dreamhead.moco.util.Globs.glob(Globs.java:20)
	at com.github.dreamhead.moco.util.GlobsTest.should_glob_relative_files(GlobsTest.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)

**Comment by dreamhead** [comment]
Could you please provide your configuration files which can reproduce your failure?

**Comment by HelloXiaoHe** [comment]
is nothing special of the file,the exception throw by the junitTest
![default](https://user-images.githubusercontent.com/23098688/35467318-cb1bfbf2-0347-11e8-9fa3-7de44ba075f6.png)
![default](https://user-images.githubusercontent.com/23098688/35467363-70d98708-0348-11e8-87e3-6d28217d572a.png)

data.json:

[
{ "request" : { "uri" : "/index" }, 
"response" : { "json": {
		  "code":"200",
		  "desc":"这个是index"
		}} 
},

{ "request" : { "uri" : "/hello" }, "response" : { "text" : "Hello  World !!!" } },
{ "request" : { "uri" : "/redirect" }, "redirectTo" : "http://www.baidu.com" },
{ 
 "request" : { 
    "uri" : "/user/getUser",
     "queries": { "name":"henry" ,"pwd":"123"} 
  },
  "response" : {
	   "headers":{"content-type": "application/json"},
       "text" : "Hey. I'm 大英雄123"
     }  
},

{ 
 "request" : { 
    "uri" : "/user/getUser",
     "queries": { "name":"henry" } 
  },
  "response" : {
	   "headers":{"content-type": "application/json"},
       "text" : "Hey. I'm 大英雄"
     }  
},
 {
      "request": {
      "uri": "/test1",
      "method": "GET"
    },
      "response": {
	  "status":500,
      "json": {
		  "code":"200",
		  "desc":" GET success "
		}
	}
 } 
]

other.json
[
{ "request" : { "uri" : "/index2" }, 
"response" : { "json": {
		  "code":"200",
		  "desc":"这个是index2222222222"
		}} 
}
]
