### ISSUE TITLE
加载xml文件报错...

### ISSUE THREAD

**Issue by tangmaple** [dreamhead/moco#228]
准备条件：
xml文件名为：socketbyxml.xml，内容如下：
<? xml version="1.0" encoding="UTF-8"?>
<struct>
	<data name="MODULE_ID">
		<field length="2" scale="0" type="string">DP</field>
	</data>
</struct>

应用xml文件的json文件名为:socktbyxmlfile.json,内容如下：
[{
   "request":
     {
        "file":
          {
            "xml": "socketbyxml.xml"
          }
    },
  "response":
    {
      "text": "foo"
    }
}
]

1、执行：java -jar moco-runner-0.10.2-standalone.jar socket -p 12306 -c socktbyxmlfile.json
2、访问: http://127.0.0.1:12306
3、后台提示报如下错误：
[Fatal Error] :1:1: 前言中不允许有内容。
08 二月 2018 11:39:00 [nioEventLoopGroup-3-2] ERROR Exception thrown
java.lang.RuntimeException: No handler found for request: GET / HTTP/1.1
Host: localhost:12306
Connection: keep-alive
User-Agent: Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
Upgrade-Insecure-Requests: 1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9
Cookie: Idea-c5206eab=01075746-55b7-46dc-8326-788de8e044c3

        at com.github.dreamhead.moco.internal.MocoSocketHandler.handleSession(MocoSocketHandler.java:68) [moco-runner-0.10.2-standalone.jar:0.10.2]
        at com.github.dreamhead.moco.internal.MocoSocketHandler.channelRead0(MocoSocketHandler.java:41) [moco-runner-0.10.2-standalone.jar:0.10.2]
        at com.github.dreamhead.moco.internal.MocoSocketHandler.channelRead0(MocoSocketHandler.java:22) [moco-runner-0.10.2-standalone.jar:0.10.2]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [moco-runner-0.10.2-standalone.jar:0.10.2]

**Comment by dreamhead** [comment]
@chongbo2013 You can use HTML as content, not configuration.
