### ISSUE TITLE
tcp socket api fail

### ISSUE THREAD

**Issue by guoyinqiuQAX** [dreamhead/moco#246]
my RESPONSE file is 123.json,

[
{
"description":"yyy",
  "request":{
  "xpaths":{
  "/request/translation/id/text()":"99"
  }
 },
  "response":{
  "text":"<good></good>"  
  }
}
]

when I start the moco server use cammand:
java -jar moco-runner-0.12.0-standalone.jar http -p 12306 -c 123.json
and send xml to the moco server ,can have successful response
request http+xml(post):
http://localhost:12306
<?xml version="1.0" encoding="UTF-8" ?>
<request>
<translation>
<id>99</id>
</translation>
<jj>88</jj>
</request>
but when I start the moco server use cammand:
java -jar moco-runner-0.12.0-standalone.jar socket -p 12306 -c 123.json,
and send TCP to the moco server,it will be failed,plese help me to solve the problem.

**Comment by guoyinqiuQAX** [comment]
log.txt:

C:\package>java -jar moco-runner-0.12.0-standalone.jar socket -p 12306 -c 123.json
27 八月 2018 15:10:47 [main] INFO  Server is started at 12306
27 八月 2018 15:10:48 [main] INFO  Shutdown port is 55410
27 八月 2018 15:10:53 [nioEventLoopGroup-3-2] INFO  Request received:

<?xml version="1.0" encoding="UTF-8" ?>
<request>
<translation>
<id>99</id>
</translation>
<jj>88</jj>
</request>

27 八月 2018 15:10:53 [nioEventLoopGroup-3-2] ERROR Exception thrown
com.github.dreamhead.moco.MocoException: No handler found for request: <?xml version="1.0" encoding="UTF-8" ?>
<request>
<translation>
<id>99</id>
</translation>
<jj>88</jj>
</request>
        at com.github.dreamhead.moco.internal.MocoSocketHandler.handleSession(MocoSocketHandler.java:69)
        at com.github.dreamhead.moco.internal.MocoSocketHandler.channelRead0(MocoSocketHandler.java:42)
        at com.github.dreamhead.moco.internal.MocoSocketHandler.channelRead0(MocoSocketHandler.java:23)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at com.github.dreamhead.moco.internal.MocoAggregator.channelReadComplete(MocoAggregator.java:24)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:398)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:380)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelReadComplete(AbstractChannelHandlerContext.java:373)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelReadComplete(DefaultChannelPipeline.java:1364)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:398)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:380)
        at io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete(DefaultChannelPipeline.java:941)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:146)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        at io.netty.channel

**Comment by guoyinqiuQAX** [comment]
[log.txt](https://github.com/dreamhead/moco/files/2322837/log.txt)

**Comment by guoyinqiuQAX** [comment]
![tcpxml](https://user-images.githubusercontent.com/42731382/44646685-5c52e280-aa0e-11e8-8cd1-c493b77eb540.png)
