### ISSUE TITLE
moco-runner-1.0.0-standalone.jar start error 

### ISSUE THREAD

**Issue by tytyty123** [dreamhead/moco#279]
help?

Exception in thread "main" java.lang.UnsupportedClassVersionError: com/github/dreamhead/moco/bootstrap/Main : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:124)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:260)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:56)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:195)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:252)
	at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:320)
Could not find the main class: com.github.dreamhead.moco.bootstrap.Main. Program will exit.

**Comment by dreamhead** [comment]
It seems you are using a lower version Java.  You can try Moco with Java 8 or higher.
