### ISSUE TITLE
maven run test with moco jsonHttpServer throw java.lang.RuntimeException: java.lang.IllegalArgumentException: unknown configuration :[Z@767df8bd

### ISSUE THREAD

**Issue by jason-UA** [dreamhead/moco#316]
java 1.8, moco 1.3
**run test at idea will success, but run maven test will fail!**
`    void test_update_config() throws Exception {
        ContentResource resource = pathResource("SAFRMockService.json");
        final HttpServer server = jsonHttpServer(8080, resource);
        running(server, () -> {
            final MvcResult result = sendUpdateConfigRequest();
            StatusResponse responses = mapper.readValue(result.getResponse().getContentAsString(), StatusResponse.class);
            assertThat(responses.isStatus()).isEqualTo(true);
            MSConfig databaseConfig = Converter.copy(this.configDao.getSafrConfig()).to(MSConfig.class);
            MSConfig requestConfig = Converter.copy(safrConfigRequest).to(MSConfig.class);
            assertThat(requestConfig).isEqualTo(databaseConfig);
        });
    }`

`[ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 7.364 s <<< FAILURE! - in com.ms.safr.controller.ConfigIntegrationTest
[ERROR] test_update_config  Time elapsed: 0.213 s  <<< ERROR!
java.lang.RuntimeException: java.lang.IllegalArgumentException: unknown configuration :[Z@767df8bd
        at com.ms.safr.controller.ConfigIntegrationTest.test_update_config(ConfigIntegrationTest.java:60)
Caused by: java.lang.IllegalArgumentException: unknown configuration :[Z@767df8bd
        at com.ms.safr.controller.ConfigIntegrationTest.test_update_config(ConfigIntegrationTest.java:60)

`

**Comment by shiliangui** [comment]
![image](https://user-images.githubusercontent.com/111634122/185850094-8b51c8e0-7b98-4eea-97d9-213e89d5976e.png)
在jcoco的插件配置中增加红色区域

**Comment by ComeonBug** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
